#!/bin/bash

info() {
cat << EOF
####################################################
#                                                  #
# Pgit by Kfir Man                                 #
# ------------------------------------------------ #
# pgit is a script to simplify the git commands    #
# Copy this script to your /bin/ folder            #
# sudo chmod ugo+x /bin/pgit                       #
# Usage:                                           #
# pgit -a "[Commit Massage]" # commit + push       #
# pgit -p                    # pull                #
# pgit -h                    # help                #
#                                                  #
####################################################
EOF
if [[ $1 ]]; then
	exit 0
else
	exit 1
fi
}

OPTIONS=":hpa:"
if ( ! getopts "$OPTIONS" OPT); then
	echo -e "\e[31mERROR:\e[0m Invalid option!"
	info
fi

while getopts "$OPTIONS" OPT; do
	case $OPT in
		h) info true && MSG=false;;
		p) git pull origin master && MSG=false;;
		a) MSG=$OPTARG && ALL=1;;
		:) echo -e "\e[31mERROR:\e[0m Option -$OPTARG requires some value." && info;;
		\?) echo -e "\e[31mERROR:\e[0m Invalid option: -$OPTARG" && info;;
	esac
done

if [[ "$ALL" == 1 ]]; then
	git commit -a -m "$MSG"
	git push origin master
fi

exit 0