#!/bin/bash

info() {
cat << EOF
####################################################
#                                                  #    
# Pgit by Kfir Man                                 #
# ------------------------------------------------ #
# pgit is a script to simplify the git commands    #                                  
# Copy this script to your /bin/ folder            #
# sudo chmod ugo+x /bin/pgit                       #
# Usage:                                           #
# pgit -a "[Commit Massage]" # commit + push       #
# pgit -p                    # pull                #
#                                                  #
####################################################
EOF
exit 0
}


OPTIONS=":hpa:"
if ( ! getopts "$OPTIONS" OPT); then
	echo "ERROR: Invalid option!"
	exit 1
fi

while getopts "$OPTIONS" OPT; do
	case $OPT in
		h) info && MSG=false;;
		p) git pull origin master && MSG=false;;
		a) MSG=$OPTARG && ALL=1;;
		:) echo "ERROR: Option -$OPTARG requires some value." && exit 1;;
		\?) echo "ERROR: Invalid option: -$OPTARG" && exit 1;;
	esac
done

if [ -z "$MSG" ]; then
	echo "Commit massage can not be empty!"
	echo "Usage: pgit [Commit Massage]"
	exit 1
elif [[ "$ALL" == 1 ]]; then
	git commit -a -m "$MSG"
	git push origin master
fi

exit 0